# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDefaultSuite():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test3(self):
    # Test name: Test3
    # Step # | name | target | value
    # 1 | open | /de/ | 
    self.driver.get("http://selenium1py.pythonanywhere.com/de/")
    # 2 | setWindowSize | 1920x906 | 
    self.driver.set_window_size(1920, 906)
    # 3 | click | id=login_link | 
    self.driver.find_element(By.ID, "login_link").click()
    # 4 | click | id=id_registration-email | 
    self.driver.find_element(By.ID, "id_registration-email").click()
    # 5 | type | id=id_registration-email | Undine@mail.ru
    self.driver.find_element(By.ID, "id_registration-email").send_keys("Undine@mail.ru")
    # 6 | type | id=id_registration-password1 | Traudich45!
    self.driver.find_element(By.ID, "id_registration-password1").send_keys("Traudich45!")
    # 7 | type | id=id_registration-password2 | Traudich45!
    self.driver.find_element(By.ID, "id_registration-password2").send_keys("Traudich45!")
    # 8 | click | name=registration_submit | 
    self.driver.find_element(By.NAME, "registration_submit").click()
  
